import { FC, PropsWithChildren, Suspense } from "react";

import type { Metadata } from "next";

import avertastdFont from "@/lib/localFont";
import AppQueryClientProvider from "@/provider/AppQueryClientProvider";

import "@/styles/globals.css";
import { ProductProvider } from "@/context/productContext";
import BottomSheetManager from "@/containers/categoriesListPage/components/BottomSheets";
import { FormProvider } from "@/context/formContext";

export const metadata: Metadata = {
  title: "BulletGiftCards",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en" dir="ltr">
      <head>
        <meta
          name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
        />
      </head>
      <body className={`${avertastdFont.variable}`}>
        <Suspense fallback={<div>Loading...</div>}>
          <AppQueryClientProvider>
            <ProductProvider>
              <FormProvider>
                {children}
                <BottomSheetManager />
              </FormProvider>
            </ProductProvider>
          </AppQueryClientProvider>
        </Suspense>
      </body>
    </html>
  );
};

export default RootLayout;
