import { FC, PropsWithChildren, Suspense } from "react";

import type { Metadata, Viewport } from "next";

import avertastdFont from "@/lib/localFont";
import AppQueryClientProvider from "@/provider/AppQueryClientProvider";

import "@/styles/globals.css";
import { ProductProvider } from "@/context/productContext";
import BottomSheetManager from "@/containers/categoriesListPage/components/BottomSheets";
import { FormProvider } from "@/context/formContext";

export const metadata: Metadata = {
  title: "BulletGiftCards",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en" dir="ltr">
      <body className={`${avertastdFont.variable}`}>
        <Suspense fallback={<div>Loading...</div>}>
          <AppQueryClientProvider>
            <ProductProvider>
              <FormProvider>
                {children}
                <BottomSheetManager />
              </FormProvider>
            </ProductProvider>
          </AppQueryClientProvider>
        </Suspense>
      </body>
    </html>
  );
};

export default RootLayout;
